CHANGE MASTER TO MASTER_HOST='20.20.20.5', MASTER_USER='slave2', MASTER_PASSWORD='password', MASTER_LOG_FILE='mysql-bin.000005',MASTER_LOG_POS=492, MASTER_SSL_VERIFY_SERVER_CERT=0, GET_MASTER_PUBLIC_KEY=1;
START REPLICA;

